language: "en"
early_access: false
reviews:
  profile: "assertive"
  request_changes_workflow: true
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: true
  auto_review:
    enabled: false
    drafts: false
chat:
  auto_reply: true
