PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?subject ?name ?mbox
WHERE {
  ?subject rdf:type foaf:Person .
  OPTIONAL { ?subject foaf:name ?name }
  OPTIONAL { ?subject foaf:mbox ?mbox }
}
LIMIT 100
